# To compile part1, type make part1.  Similar for other 2.
# Not a good example of a Makefile
CFLAGS=-std=c99 -Wall
CC=gcc

part1: part1.o
part2: part2.o
part3: part3.o

clean:
	-rm -f core *.o part1 part2 part3
